#!/usr/bin/env python3
"""
gen_mvp_asc.py - Generate mvp_reverb.asc for the installed LTspice 26 symbols.

Connectivity strategy: every component pin gets a FLAG (net label) placed
exactly at its pin coordinate. LTspice connects all pins/wires that share a
net label, so we never rely on fragile wire routing -- only on net names.
This sidesteps the symbol-geometry pitfalls that break hand-wired .asc files.

Installed-symbol pin offsets (rotation R0), from the .asy PIN records:
  res     : (16,16) pinA(top)   , (16,96) pinB(bottom)
  cap     : (16, 0) pinA(top)   , (16,64) pinB(bottom)
  ind     : (16,16) pinA(top)   , (16,96) pinB(bottom)
  diode   : (16, 0) K(cathode)  , (16,64) A(anode)
  voltage : ( 0,16) plus        , ( 0,96) minus
  UniversalOpamp2 : (-32,16) IN+ , (-32,-16) IN- , (0,-32) V+ , (0,32) V- , (32,0) OUT
"""

OPA_PARAMS = "Avol=1Meg GBW=8Meg Slew=20Meg Ilimit=25m Rail=0 Rinc=1T"

class Asc:
    def __init__(self):
        self.lines = ["Version 4", "SHEET 1 2400 1600"]
        self.y = 16  # rolling y for auto-placed rows (unused; explicit coords below)

    def text(self, x, y, s, size=2):
        self.lines.append(f"TEXT {x} {y} Left {size} {s}")

    def flag(self, x, y, name):
        self.lines.append(f"FLAG {x} {y} {name}")

    def wire(self, x1, y1, x2, y2):
        self.lines.append(f"WIRE {x1} {y1} {x2} {y2}")

    def _sym(self, kind, x, y, rot, name, attrs):
        self.lines.append(f"SYMBOL {kind} {x} {y} {rot}")
        self.lines.append(f"SYMATTR InstName {name}")
        for k, v in attrs:
            self.lines.append(f"SYMATTR {k} {v}")

    # --- components: place at (x,y), label each pin's net via FLAG at pin coord ---
    def res(self, name, value, x, y, na, nb):
        self._sym("res", x, y, "R0", name, [("Value", value)])
        self.flag(x+16, y+16, na); self.flag(x+16, y+96, nb)

    def cap(self, name, value, x, y, na, nb):
        self._sym("cap", x, y, "R0", name, [("Value", value)])
        self.flag(x+16, y+0, na); self.flag(x+16, y+64, nb)

    def ind(self, name, value, x, y, na, nb):
        self._sym("ind", x, y, "R0", name, [("Value", value), ("SpiceLine", "Rser=0")])
        self.flag(x+16, y+16, na); self.flag(x+16, y+96, nb)

    def diode(self, name, model, x, y, na, nk):
        # Installed diode.asy: top pin (16,0)=anode (SpiceOrder 1, n+),
        #                      bottom pin (16,64)=cathode (SpiceOrder 2, n-).
        # SPICE emits: D <top> <bottom> = D <anode> <cathode>. Conducts anode>cathode.
        self._sym("diode", x, y, "R0", name, [("Value", model)])
        self.flag(x+16, y+0, na); self.flag(x+16, y+64, nk)

    def vsrc(self, name, value, x, y, np_, nn, value2=None):
        attrs = [("Value", value)]
        if value2: attrs.append(("Value2", value2))
        self._sym("voltage", x, y, "R0", name, attrs)
        self.flag(x+0, y+16, np_); self.flag(x+0, y+96, nn)

    def opa(self, name, x, y, ninp, ninn, nvp, nvn, nout):
        self._sym("UniversalOpamp2", x, y, "R0", name,
                  [("Value", "level2"), ("Value2", OPA_PARAMS)])
        self.flag(x-32, y+16, ninp)
        self.flag(x-32, y-16, ninn)
        self.flag(x+0,  y-32, nvp)
        self.flag(x+0,  y+32, nvn)
        self.flag(x+32, y+0,  nout)

    def dump(self, path):
        open(path, "w").write("\n".join(self.lines) + "\n")


a = Asc()
a.text(16, -40, "Ghost Spring MVP - Direct Op-amp Drive Spring Reverb", 4)
a.text(16, 8, "Connectivity by net labels (FLAG at each pin). Generated by gen_mvp_asc.py for installed LTspice 26 symbols.", 2)

# Rows are spaced generously; coordinates are arbitrary since nets connect by label.
# === Power & input source ===
a.vsrc("Vpos", "15", 64, 1200, "+15V", "0")
a.vsrc("Vneg", "15", 224, 1200, "0", "-15V")
a.cap("C15", "10u", 384, 1200, "+15V", "0")
a.cap("C16", "10u", 512, 1200, "-15V", "0")
a.cap("C5", "100n", 640, 1200, "+15V", "0")
a.cap("C6", "100n", 768, 1200, "-15V", "0")
a.cap("C7", "100n", 896, 1200, "+15V", "0")
a.cap("C8", "100n", 1024, 1200, "-15V", "0")
a.text(64, 1160, "Power: idealised +/-15V. C5-C8 100n decoupling, C15/C16 10u bulk.", 2)

a.vsrc("V1", "SINE(0 100m 1k)", 64, 160, "vin", "0", value2="AC 1")

# === Stage 1: input buffer U1 ===
a.cap("C_in", "1u", 160, 144, "vin", "u1_pos")   # coupling: vin -> u1_pos
a.res("R1", "1Meg", 280, 144, "u1_pos", "0")
# Clamp HIGH: conducts when u1_pos > +15V  => anode=u1_pos, cathode=+15V
a.diode("Dclamp_p", "1N4148", 400, 96, "u1_pos", "+15V")
# Clamp LOW: conducts when u1_pos < -15V  => anode=-15V, cathode=u1_pos
a.diode("Dclamp_n", "1N4148", 400, 224, "-15V", "u1_pos")
a.opa("U1", 560, 200, "u1_pos", "u1_out", "+15V", "-15V", "u1_out")  # unity follower
a.res("R2", "100", 640, 144, "u1_out", "u1_buf")

# === Stage 2: dwell pot divider + C_drive + R_drive ===
a.res("RV1a", "5k", 760, 60, "u1_buf", "rv1_wiper")
a.res("RV1b", "5k", 760, 180, "rv1_wiper", "0")
a.cap("C_drive", "1u", 880, 144, "rv1_wiper", "drive_a")
a.res("R_drive", "560", 1000, 144, "drive_a", "tank_in")

# === Spring tank RLC ===
a.res("R_tank_in", "8", 1120, 240, "tank_in", "0")
a.ind("L_tank", "15m", 1120, 60, "tank_in", "tank_mid")
a.res("R_tank_mech", "200", 1240, 240, "tank_mid", "tk_a")
a.ind("L_tank_mech", "500m", 1240, 360, "tk_a", "tk_b")
a.cap("C_tank_mech", "10n", 1240, 480, "tk_b", "0")
a.res("R_tank_out", "2550", 1360, 60, "tank_mid", "tank_out")
a.ind("L_tank_out", "2", 1360, 240, "tank_out", "0")

# === Stage 3: recovery preamp U2 (gain 1+100k/470 ~214x) ===
a.cap("C3", "470n", 1480, 144, "tank_out", "u2_in_pos")
a.res("Rbias", "100k", 1600, 240, "u2_in_pos", "0")
a.opa("U2", 1760, 200, "u2_in_pos", "u2_inv", "+15V", "-15V", "u2_out")
a.res("Ri", "470", 1700, 360, "u2_inv", "0")
a.res("Rf", "100k", 1820, 360, "u2_out", "u2_inv")

# === Post-recovery HPF: C4 + R6 (284Hz) ===
a.cap("C4", "100n", 1940, 144, "u2_out", "hpf_out")
a.res("R6", "5.6k", 2060, 240, "hpf_out", "0")

# === Stage 4: tone RV3, mix RV2, output buffer U3 ===
a.res("RV3a", "50k", 2180, 60, "hpf_out", "rv3_wiper")
a.res("RV3b", "50k", 2180, 180, "rv3_wiper", "0")
# wet (rv3_wiper) and dry (via Rdry) both meet at mix_top
a.res("Rdry", "10k", 640, 360, "u1_buf", "mix_top")
a.res("Rwet", "0.001", 2300, 60, "rv3_wiper", "mix_top")  # ~wire (tone wiper -> RV2 top)
a.res("RV2a", "50k", 2300, 200, "mix_top", "mix_node")
a.res("RV2b", "50k", 2300, 320, "mix_node", "0")
a.cap("C_bright", "47p", 2420, 200, "mix_top", "mix_node")
a.opa("U3", 2560, 400, "mix_node", "u3_out", "+15V", "-15V", "u3_out")  # unity follower
a.res("R7", "100", 2640, 344, "u3_out", "v_out")
a.res("Rload", "47k", 2760, 344, "v_out", "0")
a.text(2640, 320, "J2 -> MC100 input (47k load)", 2)

# === Simulation directives (only ONE analysis active; LTspice rejects multiples) ===
a.text(16, 1360, "!.ac dec 100 20 20k", 2)
a.text(16, 1392, "!.meas AC gain_recovery MAX V(u2_out)", 2)
a.text(16, 1424, "!.meas AC u2_stage_gain FIND V(u2_out)/V(u2_in_pos) AT=1k", 2)
a.text(16, 1472, "Other analyses (.op, .tran 0 100m 0 1u) available - swap in for .ac as needed (one analysis at a time).", 2)

a.dump("/Users/bubblegum/projects/le-ton-juste/docs/reverb-tank/stages/mvp_reverb.asc")
print("wrote mvp_reverb.asc")
